In [1]:
import numpy as np

A = np.array([[0, 1],[2, 3],[4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# 行列積
AB = np.dot(A, B)
print(AB)
# 行列の最大値
max_AB = np.max(AB)
print(max_AB)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
